export const PRODUCTS_LOADING_SLUG = 'PRODUCTS_LOADING_SLUG'
export const PRODUCTS_FAILED_SLUG = 'PRODUCTS_FAILED_SLUG'
export const PRODUCTS_SUCCESS_SLUG = 'PRODUCTS_SUCCESS_SLUG'

export const PAGE_DETAILS_LOADING = 'PAGE_DETAILS_LOADING'
export const PAGE_DETAILS_FAILED = 'PAGE_DETAILS_FAILED'
export const PAGE_DETAILS_SUCCESS = 'PAGE_DETAILS_SUCCESS'