export const CATEGORY_LOADING = 'CATEGORY_LOADING'
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS'
export const CATEGORY_FAILED = 'CATEGORY_FAILED'

export const ADD_CATEGORY_LOADING = 'ADD_CATEGORY_LOADING'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED'